/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AM;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ANSHUL M
 */
public class prefshow extends javax.swing.JFrame {

    /**
     * Creates new form prefshow
     */
    
    public void doasloads() throws SQLException{
        
        
            budget_pref_label.setText("Budget : " + global.rs.getString("Budget"));
            //date_from_label.setText("From Date : " + date1);
            //date_to_label.setText("To Date : " + date2);
            //details_label.setText("Description : " + rs.getString("description"));
            eating_pref_label.setText("Eating Pref : " + global.rs.getString("eating_pref"));
            //destination_label.setText("Destination : " + rs.getString("Destination"));
            name_label.setText(global.rs.getString("F_Name")+" "+global.rs.getString("L_Name"));
            //nopa_label.setText("Number of Accomp. People : " + toput);
            //rating_pref_label.setText(rs.getString("Rating_pref"));
            travel_activities_label.setText("They Like " + global.rs.getString("Travel_activities"));
            Question.setText("They Like " + global.rs.getString("question"));
            Drinker.setText("Drinking Pref : " + global.rs.getString("Drinker"));
            Personality.setText("Personality :" + global.rs.getString("personality_type"));
            Cuisine.setText("Cuisine Pref : " + global.rs.getString("Cuisine"));
            AccomodationPref.setText("Accomodation Pref : " + global.rs.getString("AccomodationPref"));
            //score.setText("Comapatibility Score : " + rs.getInt("score"));
        
        
    }
    public prefshow() throws SQLException {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
        doasloads();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        name_label = new javax.swing.JLabel();
        AccomodationPref = new javax.swing.JLabel();
        Cuisine = new javax.swing.JLabel();
        Drinker = new javax.swing.JLabel();
        Personality = new javax.swing.JLabel();
        Question = new javax.swing.JLabel();
        budget_pref_label = new javax.swing.JLabel();
        eating_pref_label = new javax.swing.JLabel();
        travel_activities_label = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel9.setFont(new java.awt.Font("Garamond", 0, 36)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Preferences");

        name_label.setFont(new java.awt.Font("Garamond", 0, 48)); // NOI18N
        name_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name_label.setText("Name");

        AccomodationPref.setFont(new java.awt.Font("Garamond", 0, 20)); // NOI18N
        AccomodationPref.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AccomodationPref.setText("jLabel1");

        Cuisine.setFont(new java.awt.Font("Garamond", 0, 20)); // NOI18N
        Cuisine.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cuisine.setText("jLabel2");

        Drinker.setFont(new java.awt.Font("Garamond", 0, 20)); // NOI18N
        Drinker.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Drinker.setText("jLabel3");

        Personality.setFont(new java.awt.Font("Garamond", 0, 20)); // NOI18N
        Personality.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Personality.setText("jLabel4");

        Question.setFont(new java.awt.Font("Garamond", 0, 20)); // NOI18N
        Question.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Question.setText("jLabel5");

        budget_pref_label.setFont(new java.awt.Font("Garamond", 0, 20)); // NOI18N
        budget_pref_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        budget_pref_label.setText("jLabel6");

        eating_pref_label.setFont(new java.awt.Font("Garamond", 0, 20)); // NOI18N
        eating_pref_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eating_pref_label.setText("jLabel7");

        travel_activities_label.setFont(new java.awt.Font("Garamond", 0, 20)); // NOI18N
        travel_activities_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        travel_activities_label.setText("jLabel8");

        jButton1.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eating_pref_label, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                    .addComponent(Drinker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Question, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AccomodationPref, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Personality, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                    .addComponent(budget_pref_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(travel_activities_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Cuisine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(276, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(name_label, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(242, 242, 242))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(418, 418, 418))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(name_label, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AccomodationPref)
                    .addComponent(Cuisine))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Drinker)
                    .addComponent(Personality))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Question)
                    .addComponent(budget_pref_label))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eating_pref_label)
                    .addComponent(travel_activities_label))
                .addGap(65, 65, 65)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prefshow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prefshow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prefshow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prefshow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new prefshow().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(prefshow.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccomodationPref;
    private javax.swing.JLabel Cuisine;
    private javax.swing.JLabel Drinker;
    private javax.swing.JLabel Personality;
    private javax.swing.JLabel Question;
    private javax.swing.JLabel budget_pref_label;
    private javax.swing.JLabel eating_pref_label;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel name_label;
    private javax.swing.JLabel travel_activities_label;
    // End of variables declaration//GEN-END:variables
}
